<?php
declare(strict_types=1);
require __DIR__.'/../src/bootstrap.php';
use CredentialApi\Errors\HttpError; use CredentialApi\Errors\ValidationError; use CredentialApi\Idp\BearerToken; use CredentialApi\Validators\CredentialValidator;
function sample(): array { return ['person'=>['personName'=>['givenName'=>'Manuel','lastName'=>'Garcia'],'birthDate'=>'1998-06-05','document'=>['documentNumber'=>'MOSF100913MMSRNRA0','issuerEntityCountry'=>'MX','documentType'=>'curp']], 'userUniversities'=>[['userId'=>'A01234567','userImage'=>['url'=>'https://university.example.edu/user-images/A01234567.jpg']]], 'userNotificationsGroups'=>['mandatory'=>['student']]]; }
function ok(bool $c,string $m):void{ if(!$c)throw new RuntimeException($m); } function invalid(callable $f,string $m):void{ try{$f();}catch(ValidationError){return;} throw new RuntimeException($m); }
$tests=[]; $tests['accepts valid credential']=fn()=>ok(CredentialValidator::validate(sample())['person']['document']['documentType']==='curp','valid failed'); $tests['rejects missing document']=function(){ $c=sample(); unset($c['person']['document']); invalid(fn()=>CredentialValidator::validate($c),'missing document accepted');}; $tests['rejects missing documentType']=function(){ $c=sample(); unset($c['person']['document']['documentType']); invalid(fn()=>CredentialValidator::validate($c),'missing documentType accepted');}; $tests['rejects invalid country']=function(){ $c=sample(); $c['person']['document']['issuerEntityCountry']='XX'; invalid(fn()=>CredentialValidator::validate($c),'invalid country accepted');}; $tests['rejects empty optional string']=function(){ $c=sample(); $c['person']['personName']['secondLastName']=''; invalid(fn()=>CredentialValidator::validate($c),'empty optional accepted');}; $tests['rejects impossible date']=function(){ $c=sample(); $c['person']['birthDate']='2026-02-31'; invalid(fn()=>CredentialValidator::validate($c),'bad date accepted');}; $tests['extracts bearer token']=fn()=>ok(BearerToken::extract('Bearer abc.def.ghi')==='abc.def.ghi','bearer failed'); $tests['rejects invalid bearer']=function(){ try{BearerToken::extract('Basic x');}catch(HttpError $e){ok($e->statusCode===401,'bad status');return;} throw new RuntimeException('bad bearer accepted');}; $n=0; foreach($tests as $name=>$test){$test(); echo "✓ {$name}
"; $n++;} echo "{$n} tests passed.
";
