<?php
declare(strict_types=1);
namespace CredentialApi\Validators;
use CredentialApi\Errors\ValidationError;
final class CredentialValidator {
 private array $issues=[]; private const DOC_TYPES=['run','rut','passport','dni','cpf','curp','nie','cc','nif']; private const COURSE_TYPES=['degree','master','doctorate','fp','subject','high school','other']; private const VALUE_TYPES=['text','image','link']; private const GROUPS=['student','services','professor','alumni','online_student','tester']; private const DOC_PATTERNS=['dni'=>'/^[A-Za-z0-9]+$/','cpf'=>'/^\d{11}$/','curp'=>'/^[A-Za-z]{4}\d{6}[A-Za-z]{6}[A-Za-z0-9]{2}$/','nie'=>'/^[A-Za-z0-9]+$/','cc'=>'/^\d{9}[A-Za-z]{2}\d$/','nif'=>'/^\d{9}$/','run'=>'/^\d{7,9}[0-9Kk]?$/','rut'=>'/^\d{7,9}[0-9Kk]?$/','passport'=>'/^[A-Za-z0-9]+$/'];
 public static function validate(array $c): array { $v=new self(); $v->credential($c); if($v->issues) throw new ValidationError($v->issues); return $c; }
 private function add(string $p,string $m):void{$this->issues[]=['path'=>$p,'message'=>$m];}
 private function str(mixed $v,string $p,?int $max=null):void{ if(!is_string($v)||trim($v)===''){ $this->add($p,"{$p} is required and cannot be empty"); return;} if($max!==null&&strlen($v)>$max)$this->add($p,"{$p} must contain at most {$max} characters");}
 private function optStr(array $a,string $k,string $p,?int $max=null):void{ if(array_key_exists($k,$a)) $this->str($a[$k],$p,$max); }
 private function date(mixed $v,string $p):void{ if(!is_string($v)||preg_match('/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/',$v)!==1){$this->add($p,"{$p} must use YYYY-MM-DD format");return;} [$y,$m,$d]=array_map('intval',explode('-',$v)); if(!checkdate($m,$d,$y))$this->add($p,"{$p} must be a valid calendar date"); }
 private function enum(mixed $v,array $allowed,string $p):void{ if(!is_string($v)||!in_array($v,$allowed,true))$this->add($p,"{$p} must be one of the allowed values"); }
 private function credential(array $c):void{ if(!isset($c['person'])||!is_array($c['person'])){$this->add('person','person is required');}else{$this->person($c['person']);} $u=$c['userUniversities']??null; if(!is_array($u)||$u===[]){$this->add('userUniversities','userUniversities is required and must contain at least one item');}else foreach($u as $i=>$x)$this->university($x,"userUniversities.{$i}"); if(array_key_exists('userNotificationsGroups',$c))$this->groups($c['userNotificationsGroups']); }
 private function person(array $p):void{ if(!isset($p['personName'])||!is_array($p['personName'])){$this->add('person.personName','personName is required');}else{$this->str($p['personName']['givenName']??null,'person.personName.givenName',50);$this->str($p['personName']['lastName']??null,'person.personName.lastName',50);$this->optStr($p['personName'],'secondLastName','person.personName.secondLastName',50);} if(array_key_exists('contactPoint',$p))$this->contact($p['contactPoint']); $this->document($p['document']??null); if(array_key_exists('nationality',$p))$this->nationality($p['nationality']); $this->date($p['birthDate']??null,'person.birthDate'); }
 private function contact(mixed $c):void{ if(!is_array($c)){$this->add('person.contactPoint','contactPoint must be an object when present');return;} $this->optStr($c,'telephone','person.contactPoint.telephone'); $this->str($c['emailAddress']??null,'person.contactPoint.emailAddress'); if(isset($c['emailAddress'])&&is_string($c['emailAddress'])&&!filter_var($c['emailAddress'],FILTER_VALIDATE_EMAIL))$this->add('person.contactPoint.emailAddress','emailAddress must be valid'); }
 private function document(mixed $d):void{ if(!is_array($d)){$this->add('person.document','document is required and must be an object');return;} $this->str($d['documentNumber']??null,'person.document.documentNumber'); if(isset($d['documentNumber'])&&is_string($d['documentNumber'])&&preg_match('/^[A-Za-z0-9]+$/',$d['documentNumber'])!==1)$this->add('person.document.documentNumber','No spaces or punctuation are allowed'); $country=$d['issuerEntityCountry']??null; if(!is_string($country)||!CountryValidator::isValid($country))$this->add('person.document.issuerEntityCountry','issuerEntityCountry must be an assigned ISO 3166 Alpha-2 code'); $type=$d['documentType']??null; $this->enum($type,self::DOC_TYPES,'person.document.documentType'); if(is_string($type)&&isset(self::DOC_PATTERNS[$type])&&isset($d['documentNumber'])&&is_string($d['documentNumber'])&&preg_match(self::DOC_PATTERNS[$type],$d['documentNumber'])!==1)$this->add('person.document.documentNumber',"documentNumber does not match {$type} format"); }
 private function nationality(mixed $n):void{ if(!is_array($n)){$this->add('person.nationality','nationality must be an object when present');return;} $c=$n['countryCode']??null; if(!is_string($c)||!CountryValidator::isValid($c))$this->add('person.nationality.countryCode','countryCode must be an assigned ISO 3166 Alpha-2 code'); }
 private function university(mixed $u,string $p):void{ if(!is_array($u)){$this->add($p,'userUniversity item must be an object');return;} $this->str($u['userId']??null,"{$p}.userId"); if(array_key_exists('creationDate',$u))$this->date($u['creationDate'],"{$p}.creationDate"); if(!isset($u['userImage'])||!is_array($u['userImage'])){$this->add("{$p}.userImage",'userImage is required');}else{$this->str($u['userImage']['url']??null,"{$p}.userImage.url"); if(isset($u['userImage']['url'])&&is_string($u['userImage']['url'])&&!filter_var($u['userImage']['url'],FILTER_VALIDATE_URL))$this->add("{$p}.userImage.url",'userImage.url must be valid');} if(array_key_exists('courses',$u)){ if(!is_array($u['courses'])||$u['courses']===[])$this->add("{$p}.courses",'courses must contain at least one item when present'); else foreach($u['courses'] as $i=>$c){ if(!is_array($c)){$this->add("{$p}.courses.{$i}",'course must be an object');continue;} $this->str($c['name']??null,"{$p}.courses.{$i}.name",50); $this->enum($c['type']??null,self::COURSE_TYPES,"{$p}.courses.{$i}.type"); }} if(array_key_exists('role',$u)){ if(!is_array($u['role']))$this->add("{$p}.role",'role must be an object when present'); else $this->str($u['role']['name']??null,"{$p}.role.name"); } }
 private function groups(mixed $g):void{ if(!is_array($g)){$this->add('userNotificationsGroups','userNotificationsGroups must be an object when present');return;} if(!isset($g['mandatory'])||!is_array($g['mandatory'])||$g['mandatory']===[])$this->add('userNotificationsGroups.mandatory','mandatory notification groups are required'); else foreach($g['mandatory'] as $i=>$x)$this->enum($x,self::GROUPS,"userNotificationsGroups.mandatory.{$i}"); if(array_key_exists('optional',$g)){ if(!is_array($g['optional'])||$g['optional']===[])$this->add('userNotificationsGroups.optional','optional notification groups must contain at least one item when present'); else foreach($g['optional'] as $i=>$x)$this->str($x,"userNotificationsGroups.optional.{$i}"); } }
}
