<?php
declare(strict_types=1);
namespace CredentialApi\Security;
use CredentialApi\Errors\HttpError;
final class JwtVerifier {
 private static array $cache=[]; public function __construct(private readonly string $jwksUrl){}
 public function verify(string $jwt,string|array $issuer,string $audience):array{ [$h,$p,$signed,$sig]=$this->parse($jwt); if(($h['alg']??null)!=='RS256'||!is_string($h['kid']??null))throw new HttpError(401,'Access token is missing or invalid'); $pem=$this->pem($this->key($h['kid'])); if(openssl_verify($signed,$sig,$pem,OPENSSL_ALGO_SHA256)!==1)throw new HttpError(401,'Access token is missing or invalid'); $now=time(); if(isset($p['exp'])&&is_numeric($p['exp'])&&(int)$p['exp']<$now)throw new HttpError(401,'Access token is expired'); if(isset($p['nbf'])&&is_numeric($p['nbf'])&&(int)$p['nbf']>$now)throw new HttpError(401,'Access token is not active yet'); $issuers=is_array($issuer)?$issuer:[$issuer]; if(!is_string($p['iss']??null)||!in_array($p['iss'],$issuers,true))throw new HttpError(401,'Access token issuer is invalid'); $aud=$p['aud']??null; $auds=is_array($aud)?$aud:[$aud]; if(!in_array($audience,$auds,true))throw new HttpError(401,'Access token audience is invalid'); return $p; }
 private function parse(string $jwt):array{ $parts=explode('.',$jwt); if(count($parts)!==3)throw new HttpError(401,'Access token is missing or invalid'); [$eh,$ep,$es]=$parts; $h=json_decode(self::b64($eh),true); $p=json_decode(self::b64($ep),true); if(!is_array($h)||!is_array($p))throw new HttpError(401,'Access token is missing or invalid'); return [$h,$p,$eh.'.'.$ep,self::b64($es)]; }
 public static function b64(string $v):string{ $pad=strlen($v)%4; if($pad)$v.=str_repeat('=',4-$pad); $d=base64_decode(strtr($v,'-_','+/'),true); if($d===false)throw new HttpError(401,'Access token is missing or invalid'); return $d; }
 private function jwks():array{ if(isset(self::$cache[$this->jwksUrl])&&self::$cache[$this->jwksUrl]['exp']>time())return self::$cache[$this->jwksUrl]['data']; $json=@file_get_contents($this->jwksUrl); if($json===false)throw new HttpError(401,'Unable to validate token against identity provider'); $data=json_decode($json,true); if(!is_array($data))throw new HttpError(401,'Unable to validate token against identity provider'); self::$cache[$this->jwksUrl]=['exp'=>time()+3600,'data'=>$data]; return $data; }
 private function key(string $kid):array{ foreach(($this->jwks()['keys']??[]) as $k) if(is_array($k)&&($k['kid']??null)===$kid)return $k; throw new HttpError(401,'Access token is missing or invalid'); }
 private function pem(array $jwk):string{ $n=self::b64((string)($jwk['n']??'')); $e=self::b64((string)($jwk['e']??'')); $rsa=$this->seq($this->int($n).$this->int($e)); $alg=$this->seq($this->oid('1.2.840.113549.1.1.1')."\x05\x00"); $spki=$this->seq($alg.$this->bit($rsa)); return "-----BEGIN PUBLIC KEY-----\n".chunk_split(base64_encode($spki),64,"\n")."-----END PUBLIC KEY-----\n"; }
 private function len(int $l):string{ if($l<128)return chr($l); $b=''; while($l>0){$b=chr($l&255).$b;$l>>=8;} return chr(128|strlen($b)).$b; } private function int(string $v):string{ $v=ltrim($v,"\x00"); if($v==='')$v="\x00"; if((ord($v[0])&128)!==0)$v="\x00".$v; return "\x02".$this->len(strlen($v)).$v; } private function seq(string $v):string{return "\x30".$this->len(strlen($v)).$v;} private function bit(string $v):string{return "\x03".$this->len(strlen($v)+1)."\x00".$v;} private function oid(string $oid):string{ $p=array_map('intval',explode('.',$oid)); $out=chr($p[0]*40+$p[1]); foreach(array_slice($p,2) as $x){$s=[chr($x&127)];$x>>=7;while($x>0){array_unshift($s,chr(($x&127)|128));$x>>=7;}$out.=implode('',$s);} return "\x06".$this->len(strlen($out)).$out; }
}
